# Base Image
FROM ubuntu:20.04

# Arguments and Environment Variables
ARG RUNNER_VERSION
ARG TERRAFORM_VERSION="1.4.6"
ENV DEBIAN_FRONTEND=noninteractive

# Labels
LABEL Author="Kishore Kumar Behera"
LABEL Email="kishore.behera2010@gmail.com"
LABEL GitHub="https://github.com/unplugged-kk"
LABEL BaseImage="ubuntu:20.04"
LABEL RunnerVersion=${RUNNER_VERSION}

# Updating Ubuntu and adding a new user 'docker'
RUN apt-get update -y && apt-get upgrade -y && useradd -m docker

# Installing necessary packages
RUN apt-get install -y --no-install-recommends \
    curl nodejs wget unzip vim git azure-cli jq build-essential libssl-dev libffi-dev python3 python3-venv python3-dev python3-pip

# Downloading and extracting GitHub Runner
RUN cd /home/docker && mkdir actions-runner && cd actions-runner \
    && curl -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz

# Downloading and installing Terraform
RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Setting permissions for the 'docker' user and installing dependencies
RUN chown -R docker ~docker && /home/docker/actions-runner/bin/installdependencies.sh

# Adding and setting permissions for 'spin.sh'
ADD spin.sh spin.sh
RUN chmod +x spin.sh

# Switching to the 'docker' user
USER docker

# Setting the entry point for the container
ENTRYPOINT ["./spin.sh"]
